### ISSUE TITLE
Feature request: changeable env param

### ISSUE THREAD

**Issue by lancedikson** [heroku/heroku-buildpack-emberjs#22] opened 2017-01-31 16:09 UTC
Hey, what about make it possible to change `--production` to any other thing? For instance, I'd like to use `--staging`.

**Comment by acorncom** [comment] 2017-02-18 14:42
Believe this is close to a duplicate of https://github.com/heroku/heroku-buildpack-ember-cli-deploy/issues/3

**Comment by lancedikson** [comment] 2017-03-08 13:56
@acorncom, yep, but no moves in that issue ¯\_(ツ)_/¯

**Comment by Dhaulagiri** [comment] 2017-03-08 15:54
I think we can probably close this and try to ship #5

**Comment by lancedikson** [comment] 2017-03-08 16:04
Great! I've tested the fork made for that PR. It works for me.

**Closed as completed** 2017-03-08 16:07 UTC
